name: Deploy 🎮

on: workflow_dispatch

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:

  - name: Verify build directory
  run: |
    pwd
    ls -R build
  working-directory: build

  deployPages:
    name: Deploy to Itch.io 🚀
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Cache WebAssembly build
        uses: actions/cache@v2
        with:
          path: build
          key: ${{ runner.os }}-build-WebGL-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-WebGL-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Display structure of root files
        run: ls -R
        working-directory: build/WebGL

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: itch-io
          folder: build/WebGL

      - uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_API_KEY }}
          CHANNEL: HTML
          ITCH_GAME: CICD-Demo
          ITCH_USER: mittomrum
          BRANCH: itch-io
          PACKAGE: build/WebGL 
